package org.gwhere.permission.mapper;

import org.gwhere.permission.model.Brand;

import java.util.ArrayList;

public interface BrandMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    int insert(Brand record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brand
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    int insertSelective(Brand record);


    ArrayList<Brand> selectSelective (Brand record);
}