package org.gwhere.permission.mapper;

import org.gwhere.permission.model.Store;

public interface StoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    int insert(Store record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table store
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    int insertSelective(Store record);
}