package org.gwhere.permission.mapper;

import org.gwhere.permission.model.SysClass;

public interface SysClassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_class
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_class
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int insert(SysClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_class
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int insertSelective(SysClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_class
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    SysClass selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_class
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int updateByPrimaryKeySelective(SysClass record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_class
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int updateByPrimaryKey(SysClass record);
}