package org.gwhere.permission.mapper;

import org.gwhere.permission.model.SysCource;

public interface SysCourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cource
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cource
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int insert(SysCource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cource
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int insertSelective(SysCource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cource
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    SysCource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cource
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int updateByPrimaryKeySelective(SysCource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_cource
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int updateByPrimaryKey(SysCource record);
}