package org.gwhere.permission.mapper;

import org.gwhere.permission.model.SysCourseware;

public interface SysCoursewareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_courseware
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_courseware
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int insert(SysCourseware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_courseware
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int insertSelective(SysCourseware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_courseware
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    SysCourseware selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_courseware
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int updateByPrimaryKeySelective(SysCourseware record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_courseware
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int updateByPrimaryKey(SysCourseware record);
}