package org.gwhere.permission.mapper;

import org.gwhere.permission.model.SysStudent;

public interface SysStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int insert(SysStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int insertSelective(SysStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    SysStudent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int updateByPrimaryKeySelective(SysStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_student
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int updateByPrimaryKey(SysStudent record);
}