package org.gwhere.permission.mapper;

import org.gwhere.permission.model.SysTeacher;

public interface SysTeacherMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_teacher
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_teacher
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int insert(SysTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_teacher
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int insertSelective(SysTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_teacher
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    SysTeacher selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_teacher
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int updateByPrimaryKeySelective(SysTeacher record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_teacher
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    int updateByPrimaryKey(SysTeacher record);
}