package org.gwhere.permission.model;

import java.util.Date;

public class Brand {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_name
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_url
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    private String brandUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_img
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    private String brandImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.insert_time
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    private Date insertTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.update_time
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column brand.brand_id
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    private String brandId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_name
     *
     * @return the value of brand.brand_name
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_name
     *
     * @param brandName the value for brand.brand_name
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_url
     *
     * @return the value of brand.brand_url
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public String getBrandUrl() {
        return brandUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_url
     *
     * @param brandUrl the value for brand.brand_url
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public void setBrandUrl(String brandUrl) {
        this.brandUrl = brandUrl == null ? null : brandUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_img
     *
     * @return the value of brand.brand_img
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public String getBrandImg() {
        return brandImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_img
     *
     * @param brandImg the value for brand.brand_img
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public void setBrandImg(String brandImg) {
        this.brandImg = brandImg == null ? null : brandImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.insert_time
     *
     * @return the value of brand.insert_time
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.insert_time
     *
     * @param insertTime the value for brand.insert_time
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.update_time
     *
     * @return the value of brand.update_time
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.update_time
     *
     * @param updateTime the value for brand.update_time
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column brand.brand_id
     *
     * @return the value of brand.brand_id
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public String getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column brand.brand_id
     *
     * @param brandId the value for brand.brand_id
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public void setBrandId(String brandId) {
        this.brandId = brandId == null ? null : brandId.trim();
    }
}