package org.gwhere.permission.model;

import java.util.Date;

public class Store {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.Store_Name
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    private String storeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.Store_Adress
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    private String storeAdress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.Store_Iphone
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    private Integer storeIphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.Create_Store_Time
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    private Date createStoreTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.Update_Store_Time
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    private Date updateStoreTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column store.Store_Id
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    private String storeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.Store_Name
     *
     * @return the value of store.Store_Name
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public String getStoreName() {
        return storeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.Store_Name
     *
     * @param storeName the value for store.Store_Name
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public void setStoreName(String storeName) {
        this.storeName = storeName == null ? null : storeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.Store_Adress
     *
     * @return the value of store.Store_Adress
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public String getStoreAdress() {
        return storeAdress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.Store_Adress
     *
     * @param storeAdress the value for store.Store_Adress
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public void setStoreAdress(String storeAdress) {
        this.storeAdress = storeAdress == null ? null : storeAdress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.Store_Iphone
     *
     * @return the value of store.Store_Iphone
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public Integer getStoreIphone() {
        return storeIphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.Store_Iphone
     *
     * @param storeIphone the value for store.Store_Iphone
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public void setStoreIphone(Integer storeIphone) {
        this.storeIphone = storeIphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.Create_Store_Time
     *
     * @return the value of store.Create_Store_Time
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public Date getCreateStoreTime() {
        return createStoreTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.Create_Store_Time
     *
     * @param createStoreTime the value for store.Create_Store_Time
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public void setCreateStoreTime(Date createStoreTime) {
        this.createStoreTime = createStoreTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.Update_Store_Time
     *
     * @return the value of store.Update_Store_Time
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public Date getUpdateStoreTime() {
        return updateStoreTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.Update_Store_Time
     *
     * @param updateStoreTime the value for store.Update_Store_Time
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public void setUpdateStoreTime(Date updateStoreTime) {
        this.updateStoreTime = updateStoreTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column store.Store_Id
     *
     * @return the value of store.Store_Id
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public String getStoreId() {
        return storeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column store.Store_Id
     *
     * @param storeId the value for store.Store_Id
     *
     * @mbg.generated Fri Jul 12 11:51:18 CST 2019
     */
    public void setStoreId(String storeId) {
        this.storeId = storeId == null ? null : storeId.trim();
    }
}