package org.gwhere.permission.model;

import java.util.Date;

public class SysCategory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category.ID
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category.CATEGORY_VALUE
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private String categoryValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category.CATEGORY_NAME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private String categoryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category.STATUS
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category.CREATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category.CREATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category.LAST_UPDATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category.LAST_UPDATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private String lastUpdateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category.ID
     *
     * @return the value of sys_category.ID
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category.ID
     *
     * @param id the value for sys_category.ID
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category.CATEGORY_VALUE
     *
     * @return the value of sys_category.CATEGORY_VALUE
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public String getCategoryValue() {
        return categoryValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category.CATEGORY_VALUE
     *
     * @param categoryValue the value for sys_category.CATEGORY_VALUE
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setCategoryValue(String categoryValue) {
        this.categoryValue = categoryValue == null ? null : categoryValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category.CATEGORY_NAME
     *
     * @return the value of sys_category.CATEGORY_NAME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category.CATEGORY_NAME
     *
     * @param categoryName the value for sys_category.CATEGORY_NAME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category.STATUS
     *
     * @return the value of sys_category.STATUS
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category.STATUS
     *
     * @param status the value for sys_category.STATUS
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category.CREATE_TIME
     *
     * @return the value of sys_category.CREATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category.CREATE_TIME
     *
     * @param createTime the value for sys_category.CREATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category.CREATE_USER
     *
     * @return the value of sys_category.CREATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category.CREATE_USER
     *
     * @param createUser the value for sys_category.CREATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category.LAST_UPDATE_TIME
     *
     * @return the value of sys_category.LAST_UPDATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for sys_category.LAST_UPDATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category.LAST_UPDATE_USER
     *
     * @return the value of sys_category.LAST_UPDATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category.LAST_UPDATE_USER
     *
     * @param lastUpdateUser the value for sys_category.LAST_UPDATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser == null ? null : lastUpdateUser.trim();
    }
}