package org.gwhere.permission.model;

import java.util.Date;

public class SysCategoryItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category_item.ID
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category_item.CATEGORY_ID
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private Integer categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category_item.ITEM_VALUE
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private String itemValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category_item.ITEM_NAME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category_item.ITEM_ORDER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private Integer itemOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category_item.STATUS
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category_item.CREATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category_item.CREATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category_item.LAST_UPDATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_category_item.LAST_UPDATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private String lastUpdateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category_item.ID
     *
     * @return the value of sys_category_item.ID
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category_item.ID
     *
     * @param id the value for sys_category_item.ID
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category_item.CATEGORY_ID
     *
     * @return the value of sys_category_item.CATEGORY_ID
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category_item.CATEGORY_ID
     *
     * @param categoryId the value for sys_category_item.CATEGORY_ID
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category_item.ITEM_VALUE
     *
     * @return the value of sys_category_item.ITEM_VALUE
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public String getItemValue() {
        return itemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category_item.ITEM_VALUE
     *
     * @param itemValue the value for sys_category_item.ITEM_VALUE
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setItemValue(String itemValue) {
        this.itemValue = itemValue == null ? null : itemValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category_item.ITEM_NAME
     *
     * @return the value of sys_category_item.ITEM_NAME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category_item.ITEM_NAME
     *
     * @param itemName the value for sys_category_item.ITEM_NAME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setItemName(String itemName) {
        this.itemName = itemName == null ? null : itemName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category_item.ITEM_ORDER
     *
     * @return the value of sys_category_item.ITEM_ORDER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public Integer getItemOrder() {
        return itemOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category_item.ITEM_ORDER
     *
     * @param itemOrder the value for sys_category_item.ITEM_ORDER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setItemOrder(Integer itemOrder) {
        this.itemOrder = itemOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category_item.STATUS
     *
     * @return the value of sys_category_item.STATUS
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category_item.STATUS
     *
     * @param status the value for sys_category_item.STATUS
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category_item.CREATE_TIME
     *
     * @return the value of sys_category_item.CREATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category_item.CREATE_TIME
     *
     * @param createTime the value for sys_category_item.CREATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category_item.CREATE_USER
     *
     * @return the value of sys_category_item.CREATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category_item.CREATE_USER
     *
     * @param createUser the value for sys_category_item.CREATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category_item.LAST_UPDATE_TIME
     *
     * @return the value of sys_category_item.LAST_UPDATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category_item.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for sys_category_item.LAST_UPDATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_category_item.LAST_UPDATE_USER
     *
     * @return the value of sys_category_item.LAST_UPDATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_category_item.LAST_UPDATE_USER
     *
     * @param lastUpdateUser the value for sys_category_item.LAST_UPDATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser == null ? null : lastUpdateUser.trim();
    }
}