package org.gwhere.permission.model;

import java.util.Date;

public class SysCourseware {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_courseware.ID
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_courseware.COURCE_ID
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private Integer courceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_courseware.COURSEWARE_NAME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private String coursewareName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_courseware.COURSEWARE_URL
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private String coursewareUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_courseware.STATUS
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_courseware.CREATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_courseware.CREATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_courseware.LAST_UPDATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_courseware.LAST_UPDATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private String lastUpdateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_courseware.ID
     *
     * @return the value of sys_courseware.ID
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_courseware.ID
     *
     * @param id the value for sys_courseware.ID
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_courseware.COURCE_ID
     *
     * @return the value of sys_courseware.COURCE_ID
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public Integer getCourceId() {
        return courceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_courseware.COURCE_ID
     *
     * @param courceId the value for sys_courseware.COURCE_ID
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setCourceId(Integer courceId) {
        this.courceId = courceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_courseware.COURSEWARE_NAME
     *
     * @return the value of sys_courseware.COURSEWARE_NAME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public String getCoursewareName() {
        return coursewareName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_courseware.COURSEWARE_NAME
     *
     * @param coursewareName the value for sys_courseware.COURSEWARE_NAME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setCoursewareName(String coursewareName) {
        this.coursewareName = coursewareName == null ? null : coursewareName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_courseware.COURSEWARE_URL
     *
     * @return the value of sys_courseware.COURSEWARE_URL
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public String getCoursewareUrl() {
        return coursewareUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_courseware.COURSEWARE_URL
     *
     * @param coursewareUrl the value for sys_courseware.COURSEWARE_URL
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setCoursewareUrl(String coursewareUrl) {
        this.coursewareUrl = coursewareUrl == null ? null : coursewareUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_courseware.STATUS
     *
     * @return the value of sys_courseware.STATUS
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_courseware.STATUS
     *
     * @param status the value for sys_courseware.STATUS
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_courseware.CREATE_TIME
     *
     * @return the value of sys_courseware.CREATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_courseware.CREATE_TIME
     *
     * @param createTime the value for sys_courseware.CREATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_courseware.CREATE_USER
     *
     * @return the value of sys_courseware.CREATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_courseware.CREATE_USER
     *
     * @param createUser the value for sys_courseware.CREATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_courseware.LAST_UPDATE_TIME
     *
     * @return the value of sys_courseware.LAST_UPDATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_courseware.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for sys_courseware.LAST_UPDATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_courseware.LAST_UPDATE_USER
     *
     * @return the value of sys_courseware.LAST_UPDATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_courseware.LAST_UPDATE_USER
     *
     * @param lastUpdateUser the value for sys_courseware.LAST_UPDATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser == null ? null : lastUpdateUser.trim();
    }
}