package org.gwhere.permission.model;

import java.util.Date;

public class SysTeacher {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_teacher.ID
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_teacher.TEACHER_NUMBER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private String teacherNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_teacher.TEACHER_NAME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private String teacherName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_teacher.TEACHER_ADDRESS
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private String teacherAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_teacher.STATUS
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_teacher.CREATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_teacher.CREATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_teacher.LAST_UPDATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_teacher.LAST_UPDATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    private String lastUpdateUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_teacher.ID
     *
     * @return the value of sys_teacher.ID
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_teacher.ID
     *
     * @param id the value for sys_teacher.ID
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_teacher.TEACHER_NUMBER
     *
     * @return the value of sys_teacher.TEACHER_NUMBER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public String getTeacherNumber() {
        return teacherNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_teacher.TEACHER_NUMBER
     *
     * @param teacherNumber the value for sys_teacher.TEACHER_NUMBER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setTeacherNumber(String teacherNumber) {
        this.teacherNumber = teacherNumber == null ? null : teacherNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_teacher.TEACHER_NAME
     *
     * @return the value of sys_teacher.TEACHER_NAME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public String getTeacherName() {
        return teacherName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_teacher.TEACHER_NAME
     *
     * @param teacherName the value for sys_teacher.TEACHER_NAME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName == null ? null : teacherName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_teacher.TEACHER_ADDRESS
     *
     * @return the value of sys_teacher.TEACHER_ADDRESS
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public String getTeacherAddress() {
        return teacherAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_teacher.TEACHER_ADDRESS
     *
     * @param teacherAddress the value for sys_teacher.TEACHER_ADDRESS
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setTeacherAddress(String teacherAddress) {
        this.teacherAddress = teacherAddress == null ? null : teacherAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_teacher.STATUS
     *
     * @return the value of sys_teacher.STATUS
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_teacher.STATUS
     *
     * @param status the value for sys_teacher.STATUS
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_teacher.CREATE_TIME
     *
     * @return the value of sys_teacher.CREATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_teacher.CREATE_TIME
     *
     * @param createTime the value for sys_teacher.CREATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_teacher.CREATE_USER
     *
     * @return the value of sys_teacher.CREATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_teacher.CREATE_USER
     *
     * @param createUser the value for sys_teacher.CREATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_teacher.LAST_UPDATE_TIME
     *
     * @return the value of sys_teacher.LAST_UPDATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_teacher.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for sys_teacher.LAST_UPDATE_TIME
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_teacher.LAST_UPDATE_USER
     *
     * @return the value of sys_teacher.LAST_UPDATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public String getLastUpdateUser() {
        return lastUpdateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_teacher.LAST_UPDATE_USER
     *
     * @param lastUpdateUser the value for sys_teacher.LAST_UPDATE_USER
     *
     * @mbg.generated Thu Jul 25 23:11:17 CST 2019
     */
    public void setLastUpdateUser(String lastUpdateUser) {
        this.lastUpdateUser = lastUpdateUser == null ? null : lastUpdateUser.trim();
    }
}